const SET_COURSE_TO_INITIAL_STATE = 'SET_COURSE_TO_INITIAL_STATE'
const SET_CURRENT_COURSE = 'SET_CURRENT_COURSE'
const SET_USER_TO_INITIAL_STATE = 'SET_USER_TO_INITIAL_STATE'
const SET_CURRENT_USER = 'SET_CURRENT_USER'
const SET_CONTACT_TO_INITIAL_STATE = 'SET_CONTACT_TO_INITIAL_STATE'
const SET_CURRENT_CONTACT = 'SET_CURRENT_CONTACT'
const SET_FEEDBACK_TO_INITIAL_STATE = 'SET_FEEDBACK_TO_INITIAL_STATE'
const SET_CURRENT_FEEDBACK = 'SET_CURRENT_FEEDBACK'
const SET_ADMIN_TO_INITIAL_STATE = 'SET_ADMIN_TO_INITIAL_STATE'
const SET_CURRENT_ADMIN = 'SET_CURRENT_ADMIN'
const SET_MODAL_VISIBILITY = 'SET_MODAL_VISIBILITY'
const SET_MODAL_TO_INITIAL_STATE = 'SET_MODAL_TO_INITIAL_STATE'

export {
  SET_COURSE_TO_INITIAL_STATE,
  SET_CURRENT_COURSE,
  SET_USER_TO_INITIAL_STATE,
  SET_CURRENT_USER,
  SET_CONTACT_TO_INITIAL_STATE,
  SET_CURRENT_CONTACT,
  SET_FEEDBACK_TO_INITIAL_STATE,
  SET_CURRENT_FEEDBACK,
  SET_ADMIN_TO_INITIAL_STATE,
  SET_CURRENT_ADMIN,
  SET_MODAL_VISIBILITY,
  SET_MODAL_TO_INITIAL_STATE
}